<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<Version>1.0.0.1</Version>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="SignalRClient.old.cs" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Assembly.JwtTokenGenerator\Assembly.JwtTokenGenerator.csproj" />
	  <ProjectReference Include="..\Assembly.SR.Shared\Assembly.ChatHub.Shared.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.19.1" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="8.0.28" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.28" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="8.0.1" />
	</ItemGroup>

</Project>
