<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Controllers\AuthController-LAPTOP-01AUTO-LPK.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Controllers\AuthController-LAPTOP-01AUTO-LPK.cs" />
  </ItemGroup>

  <ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="8.0.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.28" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.28" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.28" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.28" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
  </ItemGroup>

  <ItemGroup>
		<ProjectReference Include="..\..\..\Assembies\Assembly.JwtTokenGenerator\Assembly.JwtTokenGenerator.csproj" />
		<ProjectReference Include="..\..\..\Assembies\Assembly.SR.Shared\Assembly.ChatHub.Shared.csproj" />
		<ProjectReference Include="..\pacmgr.shared\pacmgr.shared.csproj" />
	</ItemGroup>

</Project>
