<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Program-LAPTOP-01AUTO-LPK.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Program-LAPTOP-01AUTO-LPK.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.28" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.28" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
		<ProjectReference Include="..\..\..\Assembies\Assembly.LoginManager\Assembly.LoginManager.csproj" />
		<ProjectReference Include="..\pacmgr.shared\pacmgr.shared.csproj" />
	</ItemGroup>

</Project>
